# 5.16 LIST 2 DIMENSI

## Percobaan 1 pada List 2 Dimensi

In [84]:
matrik = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16],
]
print (matrik)

#List 2 Dimensi adalah sebuah list dalam list yang penggambarannya seperti sebuah matrik
#matrik diurutkan berdasarkan baris

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [85]:
matrik[1]

#matrik [1] disini berarti baris kedua

[5, 6, 7, 8]

In [69]:
matrik[0]

#matrik [0] merupakan baris pertama, matrik [1] merupakan baris kedua, dst

[1, 2, 3, 4]

## Percobaan 2 pada List 2 Dimensi

In [70]:
matrik[1][2]

#matrik [a][b] dimana [a] menyimbolkan baris dan [b] menyimbolkan kolom
#baris dihitung dengan simbol [0] untuk baris pertama, [1] untuk baris kedua, [2] untuk baris ketiga, dst
#kolom dihitung dengan simbol [0] untuk kolom pertama, [1] untuk kolom kedua, [3] untuk kolom ketiga, dst

7

## Percobaan 3 pada List 2 Dimensi

In [71]:
matrik[1][2][3]

#error karena matrik hanya disimbolkan dengan baris dan kolom 
#[1] untuk menyimbolkan baris kedua
#[2] untuk menyimbolkan kolom ketiga
#sedangkan [3] tidak menyimbolkan apapun

TypeError: 'int' object is not subscriptable

## Percobaan 4 pada List 2 Dimensi

In [7]:
matrik[1][2]=100
print(matrik[1][2])

#sudah dideklarasikan sebelumnya bahwa matrik [1][2] adalah 7
#untuk mengganti matrik tersebut kita dapat lakukan dengan seperti ini

100


## Percobaan 5 pada List 2 Dimensi

In [8]:
matrik

#dan karena sudah digantikan dengan data yang baru, maka ketika di run sekarang maka data akan secara otomatis terupdate

[[1, 2, 3, 4], [5, 6, 100, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

## Percobaan 6 pada List 2 Dimensi

In [9]:
for baris in matrik:
    print(baris)
    for kolom in baris:
        print(kolom) 

#cara memanggil anggota list
#pada kasus ini, terjadi for di dalam for, dimana ketika for baris dijalankan dan bernilai benar, 
#maka akan dilanjutkna dengan for kolom
#namun jika for yang pertama salah, maka for selanjutnya tidak akan diproses

[1, 2, 3, 4]
1
2
3
4
[5, 6, 100, 8]
5
6
100
8
[9, 10, 11, 12]
9
10
11
12
[13, 14, 15, 16]
13
14
15
16


# 5.17 TUPLES

## Percobaan 1 pada Tuples

In [8]:
angka = (0,1,1,3,4,5)

#Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya
#Jika data tidak ingin dirubah isinya, maka gunakanlah tuples
#Sedangkan jika datanya masih ingin dimanipulasi kedepannya, maka gunakanlah list

In [9]:
print(angka[0])

#[0] berarti variabel pertama, dan karena variabel pertama pada angka adalah 0, maka outputnya pun juga 0

0


## Percobaan 2 pada Tuples

In [10]:
print(angka[0:3])

#sama seperti fungsi-fungsi sebelumnya, dimana [0:3] menandakan batas output variabel
#dimana [0:3] berarti variabel pertama sampai variabel kedua, karena batas akhir tidak diinputkan

(0, 1, 1)


## Percobaan 3 pada Tuples

In [11]:
for isi in angka[0:3]:
    print(isi)
    
#sama seperti fungsi diatasnya, namun karena disini menggunakan for maka outputnya akan diproses satu-satu

0
1
1


## Percobaan 4 pada Tuples

In [12]:
angka[0] = 10

#ketika kita menggunakan tuples, maka data tidak akan bisa diubah bagaimanapun bentuknya, karena tuples sangat ketat

TypeError: 'tuple' object does not support item assignment

## Percobaan 5 pada Tuples

In [13]:
angka.append(10)

#data menggunakan tuples tidak bisa diubah, sistem tuples sangat ketat!

AttributeError: 'tuple' object has no attribute 'append'

In [17]:
angka.append[0] = 10

#data menggunakan tuples tidak bisa diubah, sistem tuples sangat ketat!

AttributeError: 'tuple' object has no attribute 'append'

## Percobaan 6 pada Tuples

In [14]:
angka.remove(5)

#data menggunakan tuples tidak bisa dihapus, sistem tuples sangat ketat!

AttributeError: 'tuple' object has no attribute 'remove'

## Percobaan 7 pada Tuples

In [24]:
angka.count(1)

#ini berarti kita menghitung berapa jumlah variabel dalam data tersebut
#pada kasus ini, angka 1 itu jumlahnya 2 sehingga output yang dihasilkan pun akan 2 

2

## Percobaan 8 pada Tuples

In [34]:
angka.index(5)

#digunakan untuk mencari dimana keberadaan variabel tersebut
#pada kasus ini angka 5 berada di variabel kelima

5

In [40]:
angka.index(6)

#karena angka 6 tidak ada pada data sehingga error

ValueError: tuple.index(x): x not in tuple

# 5.18 DICTIONARIES

## Percobaan 1 pada Dictionaries

In [35]:
data_orang = {
    "nama" : "Ketut Dogler",
    "umur" : 12,
    "apakah_singel" : False
}

#Dictionaries digunakan ketika datanya terkait satu sama lain

In [36]:
print(data_orang['nama'])

#sudah dideklarasikan sebelumnya, maka output nya pun akan sama seperti yang dideklarasikan

Ketut Dogler


In [37]:
print(data_orang['Nama'])

#python sensitif dengan huruf kecil/kapital
#dimana pada kasus ini yang dideklarasikan adalah 'nama' dengan huruf n menggunakan huruf kecil
#oleh karena itulah hasilnya menjadi error

KeyError: 'Nama'

## Percobaan 2 pada Dictionaries

In [38]:
print(data_orang.get('nama'))

#fungsi ini sama seperti fungsi print sebelumnya yaitu untuk menghasilkan output sesuai yang dideklarasikan
#namun fungsi ini berbeda bentuk dengan yang sebelumnya, sehingga kita bebas menggunakan yang mana saja

Ketut Dogler


In [39]:
print(data_orang.get('Nama'))

#sama seperti sebelumnya karena perbedaan penggunaan huruf kecil/kapital sehingga tidak ada output yang dihasilkan
#disini terdapat perbedaan output, dimana fungsi yang sebelumnya menghasilkan error
#namun fungsi ini menghasilkan 'none' yang berarti tidak ada dalam definisi

None


## Percobaan 3 pada Dictionaries

In [51]:
print(data_orang.get('tanggal_lahir'))

#karena tanggal lahir tidak didefinisikan sebelumnya, maka tidak ada output yang dihasilkan (none)

None


In [52]:
print(data_orang.get('tanggal_lahir', '2-2-2010'))

#fungsi ini untuk menambahkan variabel pada definisi
#dan data pada fungsi get ini akan ditambahkan hanya untuk satu kali saja dimana fungsi itu dideklarasikan (bersifat sementara)

2-2-2010


## Percobaan 4 pada Dictionaries

In [53]:
print(data_orang)

#fungsi get bersifat sementara, sehingga ketika disini kita print kembali data orang, 
#maka data tanggal lahir tidak masuk ke dalam data, karena yang terbaca hanyalah data yang dideklarasikan di awal 

{'nama': 'Ketut Dogler', 'umur': 12, 'apakah_singel': False, 'HP': '08123456789'}


## Percobaan 5 pada Dictionaries

In [54]:
print(data_orang["tanggal_lahir"])

#sama seperti sebelumnya, karena data tanggal lahir tidak didefinisikan di awal maka tidak akan keluar di output
#namun disini terdapat perbedaan output, untuk fungsi ini menghasilkan error, sedangkan fungsi get menghasilkan 'none'

KeyError: 'tanggal_lahir'

## Percobaan 6 pada Dictionaries

In [55]:
data_orang['HP'] = '08123456789'

#data HP didefinisikan BUKAN menggunakan fungsi get

In [56]:
print(data_orang["HP"])

#menghasilkan output sesuai definisi

08123456789


## Percobaan 7 pada Dictionaries

In [57]:
print(data_orang)

#karena data HP didefinisikan TIDAK dengan menggunakan fungsi get, maka datanya akan bersifat SELAMANYA
#berbeda dengan data tanggal lahir yang didefinisikan dengan menggunakan fungsi GET yang bersifat SEMENTARA

{'nama': 'Ketut Dogler', 'umur': 12, 'apakah_singel': False, 'HP': '08123456789'}


## Latihan Dictionaries

In [59]:
angka = {
    "0" : "nol",
    "1" : "satu",
    "2" : "dua",
    "3" : "tiga",
    "4" : "empat",
    "5" : "lima",
    "6" : "enam",
    "7" : "tujuh",
    "8" : "delapan",
    "9" : "sembilan"
}

In [60]:
nomor_HP = input("Masukkan nomor HP anda ")
nomor_angka = ""
for isi in nomor_HP:
    nomor_angka += angka.get(isi) + " "
print(nomor_angka)

#program untuk merubah nomor HP yang tadinya berupa angka menjadi sebutan bilangan tersebut

Masukkan nomor HP anda 08123456
nol delapan satu dua tiga empat lima enam 


# 5.19 FUNGSI

## Percobaan 1 pada Fungsi

In [66]:
def full_name(first_name, last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")
    
#contoh pendefinisian fungsi agar ketika dibutuhkan tinggal kita panggil saja

In [67]:
first_name = input("Nama depan anda adalah ")
last_name = input("Nama belakang anda adalah ")
full_name(first_name, last_name)

#contoh pemanggilan fungsi

Nama depan anda adalah Marsanda
Nama belakang anda adalah Putri
Nama lengkapnya adalah Marsanda Putri


## Tugas Fungsi

In [ ]:
#ada dua jenis tugas fungsi yaitu menjalankan perintah dan menampilkan hasil perhitungan

In [1]:
def waktu_sampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    print(waktu)

In [2]:
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu

In [3]:
waktu_sampai(80,60)

1.3333333333333333


In [4]:
waktu_tempuh(80,60)

1.3333333333333333

In [5]:
a = waktu_sampai(80,60)
print(a)

1.3333333333333333
None


In [6]:
b = waktu_tempuh(80,60)
print(b)

1.3333333333333333


## Latihan Fungsi

In [11]:
import numpy as np

In [12]:
def luas_segitiga(alas,tinggi):
    luas=(1/2)*alas*tinggi
    return luas
def luas_lingkaran(jari_jari):
    luas=np.pi*(jari_jari**2)
    return luas
def luas_persegi(sisi):
    luas=sisi**2
    return luas
def luas_persegi_panjang(panjang,lebar):
    luas=panjang*lebar
    return luas

In [7]:
jenis_bidang=input("Tulis jenis bidangnya ")
if jenis_bidang.upper() == 'SEGITIGA':
    alas = float(input('Berapakah panjang alasnya? '))
    tinggi = float(input('Berapakah tingginya? '))
    luas = luas_segitiga(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'LINGKARAN':
    jari_jari = float(input('Berapakah panjang jari-jarinya? '))
    luas = luas_lingkaran(jari_jari)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif (jenis_bidang.upper() == 'PERSEGI') or (jenis_bidang.upper() == 'BUJUR SANGKAR'):
    sisi = float(input('Berapakah panjang sisinya? '))
    luas = luas_persegi(sisi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI PANJANG':
    panjang = float(input('Berapakah panjangnya? '))
    lebar = float(input('Berapakah lebarnya? '))
    luas = luas_persegi_panjang(panjang, lebar)
    print(f"Luas {jenis_bidang} adalah {luas}")
else:
    print(f"Maaf bidang {jenis_bidang} yang anda masukkan tidak ada.")
    print("Pilihan cuma SEGITIGA, LINGKARAN, PERSEGI dan PERSEGI PANJANG.")
    print('Terimakasih')
    
#program ini digunakan untuk menghitung luas segitiga, lingkaran, persegi, dan persegi panjang
#selain dari pada itu akan diberikan peringatan bagi bidang lain yang tidak termasuk perhitungan

Tulis jenis bidangnya jajar genjang
Maaf bidang jajar genjang yang anda masukkan tidak ada.
Pilihan cuma SEGITIGA, LINGKARAN, PERSEGI dan PERSEGI PANJANG.
Terimakasih


# 5.20 NUMPY

## 5.20.1 Perintah Dasar

### Percobaan 1 Perintah Dasar pada Numpy

In [9]:
import numpy as np

#digunakan untuk memanggil library numpy
#numpy merupakan salah satu library dalam python yang memiliki keunggulan,
#baik itu dalam perhitungan menggunakan vektor maupun matrik dalam berbagai dimensi

In [5]:
a = np.array([0,1,2,3,4])
print(a)

#fungsi print dijalankan sama seperti sebelumnya

[0 1 2 3 4]


In [6]:
b = np.array([[5,6,7,8],[9,8,7,6]])
print(b)

#output dihasilkan satu-satu secara berurutan

[[5 6 7 8]
 [9 8 7 6]]


In [7]:
c = np.array ([[[0,1,2,3],[4,5,6,7]],
               [[8,9,8,7],[6,5,4,3]],
               [[1,2,3,4],[5,6,7,8]]])
print(c)

#output dihasilkan satu-satu secara berurutan

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


### Percobaan 2 Perintah Dasar pada Numpy

In [8]:
a.ndim

#fungsi ndim berarti menghitung jumlah dimensi dari variabel
#disini berarti terdapat 1 dimensi

1

In [9]:
b.ndim

#disini berarti terdapat 2 dimensi

2

In [10]:
c.ndim

#disini berarti terdapat 3 dimensi

3

### Percobaan 3 Perintah Dasar pada Numpy

In [11]:
a.shape

#fungsi shape berarti menampilkan bentuk dari variabel tersebut (yaitu batas berupa angka), baik itu vektor maupun matrik
#pada kasus ini berarti terdapat 5 kolom dalam bentuk vektor

(5,)

In [12]:
b.shape

#ini berarti terdapat 2 baris dan dalam tiap baris terdapat 4 kolom dalam bentuk matrik

(2, 4)

In [13]:
c.shape

#ini berarti terdapat 3 baris yang dalam tiap baris terdapat 2 baris lagi, dan di tiap baris tersebut terdapat 4 kolom
#variabel ini berbentuk matrik

(3, 2, 4)

## 5.20.2 Memanggil Anggota, Kolom dan Baris

### Percobaan 1 Memanggil Anggota, Kolom dan Baris pada Numpy

In [10]:
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(d)

#pendefinisian variabel sekaligus menjalankan fungsi print sama seperti sebelumnya

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
d[0,3]

#sama seperti sub judul pembahasan kita kali ini yaitu memanggil anggota, kolom dan baris,
#maka program ini digunakan untuk menampilkan anggota, kolom dan baris pada variabel tersebut
#dalam kasus ini, kita memanggil anggota [0] yaitu anggota pertama yang berada di kolom [3] yaitu kolom keempat

4

### Percobaan 2 Memanggil Anggota, Kolom dan Baris pada Numpy

In [17]:
d[1,:]

#disini berarti kita memanggil anggota [1] yaitu anggota yang berada di urutan kedua
#dan karena tidak ada kolom yang didefinisikan [:], maka semua anggota [1] dipanggil

array([5, 6, 7, 8])

In [18]:
d[:,2]

#tidak didefinisikan [:] anggota ke berapa yang dipanggil
#namun dipanggil kolom [2] yaitu kolom yang berada di urutan ketiga 
#sehingga yang terpanggil adalah seluruh anggota yang berada di kolom [2]

array([ 3,  7, 11])

### Percobaan 3 Memanggil Anggota, Kolom dan Baris pada Numpy

In [19]:
d[0,1:3]

#dipanggil anggota [0] yaitu anggota yang berada dalam urutan pertama
#kemudian dipanggil kolom [1:3] yaitu kolom dengan urut kedua sampai kolom dengan urut ketiga
#sehingga yang terpanggil adalah kolom [1:3] dalam anggota [0]

array([2, 3])

In [20]:
d[0,0:3:2]

#dipanggil anggota [0] yaitu anggota yang berada dalam urutan pertama
#kemudian dipanggil kolom [0:3:2] yaitu dipanggil dari kolom [0] sampai kolom [3], namun diloncati 2 kali
#sehingga yang terpanggil adalah kolom [0:3:2] dalam anggota [0]

array([1, 3])

### Percobaan 4 Memanggil Anggota, Kolom dan Baris pada Numpy

In [21]:
d[0,0] = 100
print(d)

#fungsi ini digunakan untuk merubah variabel 
#variabel yang diubah dalam fungsi ini adalah variabel yang berada pada anggota [0] kolom [0]

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


## 5.20.3 Matrix

### Percobaan 1 Matrix pada Numpy

In [14]:
np.ones((2,3))

#fungsi ini digunakan untuk membuat berbagai jenis matrix
#pada kasus ini, karena menggunakan fungsi ones maka outputnya adalah matrix satu dengan 2 baris dan 3 kolom

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.zeros((3,2))

#disini menggunakan fungsi zeros yaitu matrix nol dengan 3 baris dan 2 kolom

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Percobaan 2 Matrix pada Numpy

In [16]:
np.identity(4)

#disini menggunakan matrix identitas dengan jumlah baris dan kolom sama yaitu 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Percobaan 3 Matrix pada Numpy

In [17]:
np.ones((2,3,4))

#disini menggunakan matrix satu dengan 2 baris, dan tiap barisnya memiliki 3 baris lagi yang memiliki 4 kolom

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### Percobaan 4 Matrix pada Numpy

In [18]:
np.full((3,2),9)

#disini menggunakan matrix full dengan isi angka 9
#dan terdapat 3 baris dan 2 kolom pada matrix tersebut

array([[9, 9],
       [9, 9],
       [9, 9]])

### Percobaan 5 Matrix pada Numpy

In [31]:
np.random.rand(4,3)

#matrix ini menggunakan 4 baris dan 3 kolom
#program random.rand akan menghasilkan nomor acak yang berbeda saat menjalankan kode yang sama beberapa kali

array([[0.9339875 , 0.82271035, 0.65433692],
       [0.27588499, 0.61652456, 0.41042106],
       [0.90102323, 0.13502807, 0.17165362],
       [0.05564929, 0.4341856 , 0.2068507 ]])

### Percobaan 6 Matrix pada Numpy

In [20]:
np.random.randint(1,10,size=(3,4))

#matrix ini menggunakan 3 baris dan 4 kolom
#program random.randint akan menghasilkan sebuah angka dengan tipe data integer acak dari parameter yang diberikan
#dalam kasus ini parameternya adalah 1,10

array([[1, 6, 4, 2],
       [2, 2, 1, 6],
       [9, 4, 2, 2]])

### Latihan Matrix pada Numpy

In [21]:
a = np.zeros((10,10))
print(a)

#beberapa contoh program untuk membuat matrik ukuran 10 × 10

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [22]:
b = np.identity(10)
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [23]:
c = 9*b
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [24]:
d = np.ones((8,8))
e = np.identity(8)*8
f = d+e
print(f)

[[9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9.]]


In [26]:
c[1:-1,1:-1] = f
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 9. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 9. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 9. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 9. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [27]:
g = np.identity(6)*9
c[2:-2,2:-2] = g
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 9. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 9. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [28]:
h = np.ones((4,4))*2
i = np.identity(4)*7
j = h+i
print(j)

[[9. 2. 2. 2.]
 [2. 9. 2. 2.]
 [2. 2. 9. 2.]
 [2. 2. 2. 9.]]


In [29]:
c[3:-3,3:-3] = j
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [30]:
k = np.identity(2)*9
c[4:-4,4:-4] = k
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 0. 2. 0. 1. 0.]
 [0. 1. 0. 2. 0. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


## 5.20.4 Copy

### Percoban 1 Copy pada Numpy

In [32]:
a = np.array([1,2,3,4,5])
print(a)

#pendefinisian variabel a serta perintah print a

[1 2 3 4 5]


In [33]:
b = a 
print(b)

#pendefinisian bahwa variabel b sama dengan a kemudian perintah print b

[1 2 3 4 5]


In [34]:
b[0] = 10
print(b)

#perubahan anggota variabel b pertama yang awalnya merupakan angka 1 berubah menjadi angka 10

[10  2  3  4  5]


In [35]:
print(a)

#karena variabel a sudah didefinisikan sama dengan variabel b dan mengalami perubahan anggota variabel,
#maka ketika dipanggil kembali hasilnya adalah anggota variabel yang baru

[10  2  3  4  5]


### Percoban 2 Copy pada Numpy

In [36]:
c = np.array([1,2,3,4,5])
print(c)

#kita bandingkan dengan menggunakan fungsi copy pada numpy
#disini didefinisikan variabel c kemudian perintah print c

[1 2 3 4 5]


In [37]:
d = c.copy()
print(d)

#disini didefinisikan variabel d merupakan copyan dari variabel c, TANPA mengubah anggota variabel c itu sendiri

[1 2 3 4 5]


In [38]:
d[0] = 10
print(d)

#anggota variabel pertama dari d dirubah dari angka 1 menjadi angka 10

[10  2  3  4  5]


In [39]:
print(c)

#karena sebelumnya variabel d hanya mengcopy variabel c tanpa mengubah anggota dari variabel c itu sendiri,
#maka ketika dipanggil kembali, anggota dari variabel c tidak ada yang berubah

[1 2 3 4 5]


## 5.20.5 Operasi Matematika

### Percobaan 1 Operasi Matematika pada Numpy (1 variabel)

In [40]:
a+2

#karena disini tidak didefinisikan variabel a, maka variabel yang digunakan adalah variabel a pada percobaan sebelumnya
#penjumlahan sebuah variabel dengan sebuah angka

array([12,  4,  5,  6,  7])

In [41]:
a-2

#pengurangan sebuah variabel dengan sebuah angka

array([8, 0, 1, 2, 3])

In [42]:
a*2

#perkalian sebuah variabel dengan sebuah angka

array([20,  4,  6,  8, 10])

In [43]:
a/2

#pembagian sebuah variabel dengan sebuah angka

array([5. , 1. , 1.5, 2. , 2.5])

In [44]:
a**2

#perpangkatan sebuah variabel dengan sebuah angka

array([100,   4,   9,  16,  25], dtype=int32)

### Percobaan 2 Operasi Matematika pada Numpy (2 variabel)

In [45]:
b = np.array([6,7,8,9,10])
print(b)

#didefinisikan variabel b kemudian perintah print b

[ 6  7  8  9 10]


In [46]:
a+b

#penjumlahan dua buah variabel

array([16,  9, 11, 13, 15])

In [47]:
a-b

#pengurangan dua buah variabel

array([ 4, -5, -5, -5, -5])

In [48]:
a*b

#perkalian dua buah variabel

array([60, 14, 24, 36, 50])

In [49]:
a/b

#pembagian dua buah variabel

array([1.66666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [50]:
b**a

#perpangkatan dua buah variabel

array([60466176,       49,      512,     6561,   100000], dtype=int32)

### Percobaan 3 Operasi Matematika pada Numpy (trigonometri)

In [51]:
np.cos(a)

#cos lingkaran dari elemen variabel a

array([-0.83907153, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [54]:
np.sin(a)

#sin lingkaran dari elemen variabel a

array([-0.54402111,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [52]:
np.tan(a)

#tan lingkaran dari elemen variabel a

array([ 0.64836083, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [53]:
np.sinh(a)

#sin hiperbolik dari unsur variabel a

array([1.10132329e+04, 3.62686041e+00, 1.00178749e+01, 2.72899172e+01,
       7.42032106e+01])

In [55]:
np.cosh(a)

#cos hiperbolik dari unsur variabel a

array([1.10132329e+04, 3.76219569e+00, 1.00676620e+01, 2.73082328e+01,
       7.42099485e+01])

In [56]:
np.tanh(a)

#tan hiperbolik dari unsur variabel a

array([1.        , 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ])

In [57]:
np.sqrt(a)

#akar kuadrat dari variabel a

array([3.16227766, 1.41421356, 1.73205081, 2.        , 2.23606798])

## 5.20.6 Perkalian Matrik

### Percobaan 1 Perkalian Matrik pada Numpy

In [58]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

#pendefinisian matrik a

[[1 2 3 4]
 [5 6 7 8]]


In [59]:
b = np.array([[9,10,11,12],[13,14,15,16]])
print(b)

#pendefinisian matrik b

[[ 9 10 11 12]
 [13 14 15 16]]


In [60]:
c = a*b
print(c)

#perkalian matrik a dan b

[[  9  20  33  48]
 [ 65  84 105 128]]


In [65]:
d = np.matmul(a,b)
print(d)

#perkalian matrik menggunakan perintah matmul harus memperhatikan persyaratan
#persyaratannya adalah ukuran matrik TIDAK boleh sama
#pada kasus ini, ukuran matrik a dan b adalah sama yaitu 2 × 4 sehingga tidak bisa diproses karena tidak sesuai dengan syaratnya

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

### Percobaan 2 Perkalian Matrik pada Numpy

In [62]:
e = np.array([[9,10],[11,12],[13,14],[15,16]])
print(e)

#pendefinisian matrik e

[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [63]:
f = np.matmul(a,e)
print(f)

#perkalian matrik menggunakan perintah matmul pada kasus ini berhasil karena sesuai dengan persyaratan
#dimana matrik a berukuran 2 × 4 dan matrik e yang berukuran 4 × 2

[[130 140]
 [322 348]]


### Percobaan 3 Perkalian Matrik pada Numpy

In [64]:
g = a*e

#berbeda dengan perkalian matrik matmul, maka perkalian matrik biasa merupakan kebalikannya
#syarat perkalian matrik biasa adalah ukuran matrik harus SAMA
#sehingga dalam kasus ini menghasilkan error karena matrik a dan e memiliki ukuran yang berbeda

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

## 5.20.7 Min, Max dan Sum

### Percobaan 1 Min, Max dan Sum pada Numpy

In [72]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(a)

#pendefinisian variabel a

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [73]:
b = np.min(a)
print(b)

#mencari nilai minimal dari variabel a

1


In [74]:
c = np.min(a,axis=0)
print(c)

#axis adalah suatu area dimana data akan di plot
#pada kasus ini nilai minimal dari variabel a adalah 1, dan axis=0 menunjukkan baris 
#sehingga outputnya adalah baris dimana nilai minimal berada

[1 2 3 4]


In [75]:
d = np.min(a,axis=1)
print(d)

#pada kasus ini nilai minimal dari variabel a adalah 1, dan axis=1 menunjukkan kolom 
#sehingga outputnya adalah kolom dimana nilai minimal berada

[1 5 9]


### Percobaan 2 Min, Max dan Sum pada Numpy

In [76]:
e = np.max(a)
print(e)

#mencari nilai maksimal dari variabel a

12


In [77]:
f = np.max(a,axis=0)
print(f)

#pada kasus ini nilai maksimal dari variabel a adalah 12, dan axis=0 menunjukkan baris 
#sehingga outputnya adalah baris dimana nilai maksimal berada

[ 9 10 11 12]


In [78]:
g = np.max(a,axis=1)
print(g)

#pada kasus ini nilai maksimal dari variabel a adalah 12, dan axis=1 menunjukkan kolom
#sehingga outputnya adalah kolom dimana nilai maksimal berada

[ 4  8 12]


### Percobaan 3 Min, Max dan Sum pada Numpy

In [79]:
h = np.sum(a)
print(h)

#menjumlahkan semua elemen dari variabel a

78


In [80]:
h = np.sum(a,axis=0)
print(h)

#pada kasus ini elemen dijumlahkan berdasarkan kolom, karena axis=0 menunjukkan kolom
#jadi kolom pertama dari tiap baris dijumlahkan, selanjutnya kolom kedua dari tiap baris dijumlahkan, dst sampai kolom terakhir

[15 18 21 24]


In [81]:
i = np.sum(a,axis=1)
print(i)

#pada kasus ini elemen dijumlahkan berdasarkan baris, karena axis=1 menunjukkan baris
#jadi baris pertama dijumlahkan, selanjutnya baris kedua dijumlahkan, dst sampai baris terakhir

[10 26 42]
